bataille: structures main
	g++ structures.o main.o -o bataille.out
	
structures:
	g++ -Wall -c structures.cpp -o structures.o

main:
	g++ -Wall -c main.cpp -o main.o

clean: 
	rm -f structures.o main.o bataille.out
